Pizzeria.ASP/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Pizzeria.ASP.Models;
using Pizzeria.ASP.Services;
using Pizzeria.DAL;
using Pizzeria.DAL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pizzeria.ASP.Controllers
{
    public class CategorieController : Controller
    {

        private readonly ICategorieService _categorieService;

        public CategorieController(ICategorieService service)
        {
            _categorieService = service;
        }

        public IActionResult Index()
        {
            return View(_categorieService.GetAll());
        }

        //afficher le formulaire
        public IActionResult Create()
        {
            return View();
        }

        // traiter le formulaire
        [HttpPost]
        public IActionResult Create(CategorieAddModel form)
        {
            if (ModelState.IsValid)
            {
                _categorieService.Add(form);
                TempData["success"] = "Enregistrement effectué";
                return RedirectToAction("Index");
            }
            return View(form);
        }

        public IActionResult Delete(int id)
        {
            if (!_categorieService.Delete(id))
                return NotFound();
            TempData["success"] = $"la categorie a été supprimée";
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            CategorieEditModel model = _categorieService.GetOne(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(int id, CategorieEditModel model)
        {
            if(ModelState.IsValid)
            {
                if(!_categorieService.Update(id, model))
                    return NotFound();
                TempData["success"] = "Ok";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Pizzeria.ASP/Controllers/PlatController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Pizzeria.ASP.Models;
using Pizzeria.ASP.Security;
using Pizzeria.ASP.Services;
using Pizzeria.DAL;
using Pizzeria.DAL.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Pizzeria.ASP.Controllers
{
    [CustomAuthorization("Admin")]
    public class PlatController : Controller
    {
        private readonly PizzeriaContext _dc;
        private readonly IWebHostEnvironment _env;
        private readonly ICategorieService _catService;
        private readonly IPlatService _platService;

        public PlatController(
            ICategorieService catService,
            IPlatService platService,
            PizzeriaContext dc, 
            IWebHostEnvironment env)
        {
            _dc = dc;
            _env = env;
            _catService = catService;
            _platService = platService;
        }

        public IActionResult Index([FromQuery]int? filtre)
        {
            PlatCategorieModel model = new PlatCategorieModel
            {
                Filtre = filtre,
                Plats = _platService.GetAll(filtre),
                Categories = _catService.GetAll()
            };

            return View(model);
        }

        public IActionResult Create()
        {
            PlatAddModel model = new PlatAddModel {
                Categories = _catService.GetAll()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(PlatAddModel form)
        {
            if(ModelState.IsValid)
            {
                _platService.Create(form);
                TempData["success"] = "OK";
                return RedirectToAction("Index");
            }

            form.Categories = _catService.GetAll();

            return View(form);

        }

        public IActionResult Delete(int id)
        {
            Plat plat = _platService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Pizzeria.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzeria.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" 
          href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="_menu" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if(TempData["success"] != null)
            {
                <p>@TempData["success"]</p>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Pizzeria.ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @if(TempData["success"] != null)
    {
        <script>
            toastr.success('@TempData["success"]');
        </script>
    }
</body>
</html>

Pizzeria.ASP/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizzeria.ASP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Plat" asp-action="Index">Plats</a>
                </li>
            </ul>
        </div>
    </div>
</nav>